Apply suggestions Jorge Code Review
Assorted indentation, format and spacing issue fixes.

Co-authored-by: J. Alvarez-Jarreta <jalvarez@ebi.ac.uk>

diff --git a/scripts/utility/Bulk_CoreDB_Handover_Beta b/scripts/utility/Bulk_CoreDB_Handover_Beta
--- a/scripts/utility/Bulk_CoreDB_Handover_Beta
+++ b/scripts/utility/Bulk_CoreDB_Handover_Beta
@@ -66,7 +66,7 @@ read -p "Set run as a TEST dry run ? <yes|no> " DRY_RUN
 if [[ "${DRY_RUN^^}" == "YES" ]]; then
 	echo -e -n "${ORANGE}SAFE RUN: Handover dry test run.${NC}\n\n"
 elif [[ "${DRY_RUN^^}" == "NO" ]]; then
-	echo -e -n  "${ORANGE}REAL RUN: DB Copy will attempt to submit real jobs!!${NC}\n\n"
+	echo -e -n "${ORANGE}REAL RUN: DB Copy will attempt to submit real jobs!!${NC}\n\n"
 	sleep 2
 else
 	echo -e -n "${RED}Options are 'yes' or 'no'${NC}\n"
@@ -100,9 +100,9 @@ fi
 # Check for the right modenv is located and activated
 which handover-client
 if [ $? -eq 0 ]; then
-    echo -e -n "${GREEN}ensembl_mod_env module environment detected 'ensembl/production-tools' handover-client found! Proceeding...${NC}\n\n"
+	echo -e -n "${GREEN}ensembl_mod_env module environment detected 'ensembl/production-tools' handover-client found! Proceeding...${NC}\n\n"
 else
-    echo -e -n "${RED}Unable to locate 'handover-client' (production-tools). Ensure you have created/loaded via 'module load ensembl/production-tools'.\n"
+	echo -e -n "${RED}Unable to locate 'handover-client' (production-tools). Ensure you have created/loaded via 'module load ensembl/production-tools'.\n"
 	echo -e -n "modenv_create ensembl/production-tools production-tools && module load ensembl/production-tools'${NC}\n"
 	echo -e -n "${ORANGE}See --> https://github.com/Ensembl/ensembl-mod-env/wiki/\n\n"
 	exit 1
@@ -135,34 +135,33 @@ else
 fi
 
 ## Start HO across set of input core(s)
-for DB in $(cat $INPUT_CORES_LISTED);
-do
-SPECIES=$(echo $DB | perl -pe "s/_core_.*//");
-DESCRIPTION="${CONTEXT_DESC} $SPECIES)"
-SOURCE_URL=$($HOST details url $DB)
-if [[ "${DRY_RUN^^}" == "YES" ]]; then
-	echo -e -n "${ORANGE}\nDry-run handover test:${NC}\n\n"
-	echo -e -n "${ORANGE}handover-client --action submit --uri ${SUB_ENDPOINT} --src_uri \"${DATABASE_SERVER}${DB}\" --email \"${USER}@ebi.ac.uk\" --description \"${DESCRIPTION}\"${NC}\n"
-	echo "handover-client --action submit --uri ${SUB_ENDPOINT} --src_uri \"${DATABASE_SERVER}${DB}\" --email \"${USER}@ebi.ac.uk\" --description \"${DESCRIPTION}\"" > ${SPECIES}_HandOver-DRYRUN.${RELEASE_DESC}.${DIVISION}.log
-elif [[ "${DRY_RUN^^}" == "NO" ]]; then
-	echo -e -n "${GREEN}\nPerforming real handover: $DB${NC}\n\n"
-	handover-client \
-	--action submit \
-	--uri ${SUB_ENDPOINT} \
-	--src_uri "${DATABASE_SERVER}${DB}" \
-	--email "${USER}@ebi.ac.uk" \
-	--description "${DESCRIPTION}" 2>&1 | tee ${SPECIES}_HandOver-REAL.${RELEASE_DESC}.${DIVISION}.log
+for DB in $(cat $INPUT_CORES_LISTED); do
+	SPECIES=$(echo $DB | perl -pe "s/_core_.*//");
+	DESCRIPTION="${CONTEXT_DESC} $SPECIES)"
+	SOURCE_URL=$($HOST details url $DB)
+	if [[ "${DRY_RUN^^}" == "YES" ]]; then
+		echo -e -n "${ORANGE}\nDry-run handover test:${NC}\n\n"
+		echo -e -n "${ORANGE}handover-client --action submit --uri ${SUB_ENDPOINT} --src_uri \"${DATABASE_SERVER}${DB}\" --email \"${USER}@ebi.ac.uk\" --description \"${DESCRIPTION}\"${NC}\n"
+		echo "handover-client --action submit --uri ${SUB_ENDPOINT} --src_uri \"${DATABASE_SERVER}${DB}\" --email \"${USER}@ebi.ac.uk\" --description \"${DESCRIPTION}\"" > ${SPECIES}_HandOver-DRYRUN.${RELEASE_DESC}.${DIVISION}.log
+	elif [[ "${DRY_RUN^^}" == "NO" ]]; then
+		echo -e -n "${GREEN}\nPerforming real handover: $DB${NC}\n\n"
+		handover-client \
+			--action submit \
+			--uri ${SUB_ENDPOINT} \
+			--src_uri "${DATABASE_SERVER}${DB}" \
+			--email "${USER}@ebi.ac.uk" \
+			--description "${DESCRIPTION}" 2>&1 | tee ${SPECIES}_HandOver-REAL.${RELEASE_DESC}.${DIVISION}.log
 
-	if [[ $? == 0 ]]; then
-        echo -e -n "${GREEN}Handover done - $SPECIES${NC}\n"
-    else
-        echo "${RED}handover-client submission appears to have failed: $SPECIES${NC}"
-    fi
-	sleep 2
-else
-	echo -e -n "${ORANGE}Did not recognise 'Dry Run' param. Options are: <yes|no>.${NC}\n\n"
-fi
-echo ""
+		if [[ $? == 0 ]]; then
+			echo -e -n "${GREEN}Handover done - $SPECIES${NC}\n"
+		else
+			echo "${RED}handover-client submission appears to have failed: $SPECIES${NC}"
+		fi
+		sleep 2
+	else
+		echo -e -n "${ORANGE}Did not recognise 'Dry Run' param. Options are: <yes|no>.${NC}\n\n"
+	fi
+	echo ""
 done
 
 exit 0
